CREATE DATABASE PRUEBA_ANAR

CREATE TABLE PACIENTE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	PRIMER_NOMBRE VARCHAR(20) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(20),
	PRIMER_APELLIDO VARCHAR(20) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(20),
	DIRECCION VARCHAR(40) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	CORREO VARCHAR(30) NOT NULL,
	TIPO_IDENTIFICACION VARCHAR(15) NOT NULL,
	NUMERO_IDENTIFICACION VARCHAR(10) NOT NULL,
	CODIGO_POSTAL VARCHAR(20) 
)